---
- name: Load SSL vars
  include_vars: ../../ssl/vars/main.yml

- name: Check whether SSL certs exist
  stat:
    path: "{{ letsencrypt_dir }}/live/{{ app_domain }}/privkey.pem"
  register: ssl_privkey

# `ssl_certs_exist` is used in generating the Nginx conf below
- name: Set `ssl_certs_exist` based on result
  set_fact:
    ssl_certs_exist: "{{ ssl_privkey.stat.exists }}"

- name: Add Nginx site config for `{{ app_domain }}`
  template:
    src: site.conf.j2
    dest: /etc/nginx/sites-available/{{ app_domain }}.conf
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  notify:
    - Restart Nginx

- name: Enable Nginx site config for `{{ app_domain }}`
  file:
    src: /etc/nginx/sites-available/{{ app_domain }}.conf
    dest: /etc/nginx/sites-enabled/{{ app_domain }}.conf
    state: link
  notify:
    - Restart Nginx
